### ISSUE TITLE
Add a list of completed tasks.

### ISSUE THREAD

**Issue by varunherlekar** [varunherlekar/lets-do-it#7]

**Comment by ankitgauri26** [comment]
@varunherlekar - I can work on it. Please assign it to me.

**Comment by varunherlekar** [comment]
Done, Please start working.

**Comment by ankitgauri26** [comment]
@varunherlekar - I have done my changes. Can you create a new branch for me so that I can check-in and raise PR? I am not able to create a branch. Thanks in advance

**Comment by varunherlekar** [comment]
Done. https://github.com/varunherlekar/lets-do-it/tree/master

**Comment by ankitgauri26** [comment]
Thanks for your quick reply. Still not able to push
![image](https://user-images.githubusercontent.com/22481268/135714810-5867248a-6cd4-4b82-9627-c8e99ea70c7e.png)

**Comment by ankitgauri26** [comment]
@varunherlekar - tried won both main and master branch

**Comment by varunherlekar** [comment]
Hey @ankitgauri26 do one thing, fork thi repo. Commit your changes in that and they try to push via PR.

**Comment by varunherlekar** [comment]
You haven't forked this repo yet, as far as I can tell.

**Comment by ankitgauri26** [comment]
@varunherlekar - let me do it quickly.

**Comment by ankitgauri26** [comment]
@varunherlekar - PR has been raised successfully. Thanks for the help.

**Comment by varunherlekar** [comment]
Thanks For Your Help. :)

**Comment by varunherlekar** [comment]
It is working perfectly.
